### ISSUE TITLE
[FEAT] 알림 설정 API 연결

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#185]
## 💡 Issue

<img width="195" alt="스크린샷 2023-05-29 오후 5 24 08" src="https://github.com/fairer-iOS/fairer-iOS/assets/83629193/1efbb2c2-3a2c-4b8c-92eb-2e01b4c1018f">

알림 설정 API 연결

## 📝 Todo

- [ ] 알림 설정 API

**Comment by Guel-git** [comment]
이 이슈 클로즈 해도 될 것 같아요 ~
