### ISSUE TITLE
[SETTING] 폴더 구조 리팩토링

### ISSUE THREAD

**Issue by kimkyuchul** [fairer-iOS/fairer-iOS#87]
## 💡 Issue

- 폴더 구조를 리팩토링
<img width="353" alt="스크린샷 2023-02-21 오후 5 04 24" src="https://user-images.githubusercontent.com/25146374/220284556-839ae2dc-c59e-47f4-ac08-7f483e29a6ae.png">

## 📝 Todo

- [ ] 폴더 구조를 리팩토링

**Comment by Guel-git** [comment]
규철님, 위에 이미지 보고 제 의견을 적어봅니다 !
제가 생각하기에는 2 정도의 depth 적당할 것 같아요 ! 큰 그룹 하나에 vc를 들고 있는 작은 그룹들로요. (Home 안에 Home, SettingHomeRule / HouseWork 안에 Select, Set, Write) 그렇게 생각하는 이유는 ,, 이미 vc를 들고 있는 그룹 내부에 여러 컴포넌트 폴더들이 있어서 3 이상의 depth면 하나의 파일에 접근하기가 어려울 것 같아요 !
